baseURL = "https://schiob.com/"
languageCode = "en-us"
title = "schiob"
theme = "beautifulhugo"
googleAnalytics = "UA-114935155-1"

[Params]
  subtitle = "Code, music and food"
  logo = "img/avatar-icon.png"
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  readingTime = true
  useHLJS = true

[Author]
  name = "Santiago Chio"
  website = "page/about/"
  email = "schiob4@gmail.com"
  facebook = "schiob"
  github = "schiob"
  gitlab = "schiob"
  twitter = "schiob"
  linkedin = "santiago-chío-benavides-8518ab73"

[[menu.main]]
  name = "Blog"
  url = ""
  weight = 1

[[menu.main]]
  name = "About"
  url = "page/about/"
  weight = 3
